# Needs:
# - BUILD_ARTIFACT_NAME: The name of the artifact containing the data to copy to docker
# - DOCKER_IMAGE_NAME: The name of the Docker image to build, e.g. hathoute/java-app, node:latest, ...
# - secrets.DOCKER_USERNAME: The username of the Docker Hub account to push the image to.
# - secrets.DOCKER_PASSWORD: The password of the Docker Hub account to push the image to.

internals:
  build-image: &build_image !zipped
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ${{ BUILD_ARTIFACT_NAME }}
        path: build.zip
    - name: Unzip build artifact
      run: unzip build.zip
    - name: Build Docker image
      run: docker build -t ${{ DOCKER_IMAGE_NAME }} .

jobs:
  build-docker-hub:
    runs-on: ubuntu-latest
    steps: !unzip
      - *build_image
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push ${{ DOCKER_IMAGE_NAME }}
  build-docker-ghcr:
    runs-on: ubuntu-latest
    steps: !unzip
      - *build_image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ${{ DOCKER_IMAGE_NAME }}