# This workflow builds a Java container and pushes it to a docker registry.
# Currently supporting maven and gradle for java build, and docker hub and ghcr for docker registry.
# Needs:
## PERMISSIONS:
# - if running from a pull request:
#   - pull-requests: write (from templates/linter.yml)
## ENVIRONMENT VARIABLES:
# - JAVA_BUILD_VERSION: from templates/java.yml
# - JAVA_JDK_VERSION: from templates/java.yml

name: Deploy Java Library
on:
  workflow_call:
    inputs:
      jdk-version:
        description: 'The JDK version to use (8, 11, 15, ...)'
        required: true
        default: '17'
        type: string
      java-build-tool:
        description: 'The build tool to use (maven or gradle)'
        required: true
        default: 'maven'
        type: string
      release-version:
        description: 'Release version to tag the release with. Ignored if running from a pull request.'
        required: false
        default: ''
        type: string
    secrets:
      GITHUB_TOKEN:
        description: 'Github Token.'
        required: true

imports:
  - 'templates/linter.yml'
  - 'templates/java.yml'
  - 'templates/format.yml'

jobs:
  lint-commits:
    if: ${{ github.event_name == 'pull_request' }}
    extends: linter/lint-commits

  format-release-version:
    extends: format/release-version

  deploy-java-maven:
    extends: java/deploy-java-maven
