name: Build Java using Maven
on:
  workflow_call:

imports:
  - 'templates/linter.yml'

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "::error::This workflow can only be run on pull_request events."
          exit 1
  lint-commit:
    extends: linter/lint-commit

  mvn-build-java:
    runs-on: ubuntu-latest
    needs: lint_commits
    env:
      REVISION: ${{ github.event.pull_request.head.ref }}-SNAPSHOT
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'maven'
      - name: Build with Maven
        run: mvn -Drevision="${{ env.REVISION }}" -B clean package --file pom.xml
      - name: Compress build artifact
        run: cd target; zip -r ../target.zip *
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REVISION }}
          path: target.zip