name: Create Pull Request
on:
  create

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }}
    steps:
      - run: gh pr create --repo $REPO_NAME --assignee $BRANCH_OWNER --head $BRANCH_NAME --draft --title "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
          BRANCH_OWNER: ${{ github.actor }}
          REPO_NAME: ${{ github.repository }}

