name: Build Java using Maven
on:
  workflow_call:

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "::error::This workflow can only be run on pull_request events."
          exit 1
  lint_commits:
    runs-on: ubuntu-latest
    needs: check_pr
    steps:
      - name: Lint commits
        uses: actions-ecosystem/action-lint-commits@v1
        id: lint-commits
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          regex: '^\w+(\(.+\))?: .+' # e.g.) "feat(api): Add /users/get"
          format: markdown

      - name: Post warning comment
        uses: Hathoute/action-create-comment@v1.0.4
        if: ${{ steps.lint-commits.outputs.unmatched_commits != '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment_uid: 513522
          body: |
            The following commits needs their message changes:
            
            ${{ steps.lint-commits.outputs.unmatched_commits }}
            
            The format `<type>(<scope>): <subject>` (`^\w+(\(.+\))?: .+`) is acceptable. e.g., `feat(api): Add /users/get`
      - name: Post valid comment
        uses: Hathoute/action-create-comment@v1.0.4
        if: ${{ steps.lint-commits.outputs.unmatched_commits == '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment_uid: 513522
          body: |
            All the commit messages are valid.
            
            ✔️ Lint passed.
      - name: Fail when commits don't pass lint
        if: ${{ steps.lint-commits.outputs.unmatched_commits != '' }}
        run: |
          echo "::error::Commit messages don't pass lint, check the comment on the PR for more details."
          exit 1
  mvn-build-java:
    runs-on: ubuntu-latest
    needs: lint_commits
    env:
      REVISION: ${{ github.event.pull_request.head.ref }}-SNAPSHOT
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'maven'
      - name: Build with Maven
        run: mvn -Drevision="${{ env.REVISION }}" -B clean package --file pom.xml
      - name: Compress build artifact
        run: cd target; zip -r ../target.zip *
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REVISION }}
          path: target.zip